name: HiddenStorage
description: Make any block to a hidden storage.
version: 0.3
authors: [KaskadekingDE]
website: https://github.com/KaskadekingDE/HiddenStorage

main: de.KaskadekingDE.HiddenStorage.Main
softdepend: [WorldGuard,GriefPrevention,Towny,PlotSquared]
commands:
  hiddenstorage:
    description: Main Command
    usage: /hiddenstorage <args>
    aliases: [hs]